---
title: "CE FP"
author: "Claudia Erber"
date: "2023-05-29"
output: html_document
---

## **Statistical Analysis of Behavioral Data**

Learning how to use RStudio, RMarkdown and GitHub
- Dead line 02/06/2023

- Intensive course online from 17 to 21 May

#The present RMarkdown is the second time that I am practicing each Course Session.

#After the professor review this is the Final Paper document 

##Course Sessions Summaries:

# **Session Summary 1 Intensive Course (170523)**

- Exercise 1 very difficult, watch the videos many times before hands on, and lost time
- Exercise 2 it feels little bit easier, but had problems to find some symbols in my pc
- Exercise 3 I got to solve the symbols problem and I used the link with the answers to get more familiar with the R language
- Exercise 4 R Markdown still a challenge at moment but I like it!
#**Session Summary 1 Second Course:**
- All the exercises were done following the Exercise Solutions codes and explanation. No issues during the process. 



#**Session Summary 2(180523)**
-problem to get the doc.rmd in Git tab   
-created many repositories in Github  
#**Session Summary 2 Second Course:**
-Git already installed
-Profile in Git created
-New Repository created FinalPaperCE 
-no issues to pull, push and commit files


#**Session Summary 3(190523)**
boxplot(DML ~ Fmaturity, data = squid, xlab = "maturity stage", ylab = "DML")
#ERROR 
library(vioplot)
vioplot(DML ~ Fmaturity, data = squid, xlab = "maturity stage", ylab = "DML", col = "lightblue")
#Peter´s solution below
library(vioplot)
vioplot(DML ~ Fmaturity, data = squid, xlab = "maturity stage", ylab = "DML", col = "lightblue")
#**Session Summary 3 Second Course:**
-Error ‘>’ not meaningful for factors

#**Session Summary 4(200523)**
-Error object 'diameter' not found
-Error in resid(m1) : object 'm1' not found
-Error unexpected ',' in "hist(resid(m1)),"
# **Session Summary 4 Second Course:**
-same errors as the first time I tried to do the exercise 
- errors to find objects and to plot


# **Session Summary 5(210523)**
- no exercise was done
- summary of the course
- more details about the Final Paper

## How to make the learning sessions useful to my research?

#Number and Type of whistles emitted per behaviour
#Behaviors categories: Foraging, Traveling and Fishing
#Type of whistles: Ascending, Descending and Constant

##import the ‘whistles.txt’ file into R
whistles <- read.table('data/whistlesBE.txt', header = TRUE, stringsAsFactors = TRUE)

#use the head() function to display the first 4 rows of my dataframe
head(whistlesBE)

#use the str() function to display the structure of the dataset and a neat summary of your variables
str(whistles)

#get useful summary of your dataframe by using the summary() function
summary(whistles)

#extract all observations from the whistles dataframe and the columns Ascending, Descending and Constatnt and assign to a variable called Types.
# all rows and columns 1, 2 3
Types <- whistles[, c(2, 3, 4)]

#mean ascending whistles
mean(whistles$Ascending)

#mean descending whistles
mean(whistles$Descending)

#mean Constant whistles
mean(whistles$Constant)

#Create a pairs plot for all variables
# vanilla pairs plot
pairs(whistles[, c(1, 2, 3)])


#Create a boxplot to visualise the differences in Ascending at each Behaviour
summary(whistles)
whistlesBE <- read.table('data/whistlesBE.txt', header = TRUE, stringsAsFactors = TRUE)
summary(whistlesBE)

# convert variables to factors
whistlesBE$ascending <- factor(whistlesBE$ascending)
whistlesBE$descending <- factor(whistlesBE$descending)
whistlesBE$constant <- factor(whistlesBE$constant)

str(whistlesBE)

#Create a pairs plot for all variables
# vanilla pairs plot
pairs(whistlesBE[, c(2, 3, 4)])

boxplot(ascending ~ Behaviour, data = whistlesBE, xlab = "Behaviour", ylab = "ascending")

Foraging = 1
Traveling = 2
Fishing = 3
Socializing = 4


whistlesBEnum <- read.table('data/whistlesBEnum.txt', header = TRUE, stringsAsFactors = TRUE)
summary(whistlesBE)

pairs(whistlesBEnum[, c(3, 4, 5)])
summary(whistlesBEnum)

boxplot(ascending ~ Behaviour, data = whistlesBEnum, xlab = "Behaviour", ylab = "ascending")

barplot(ascending ~ Behaviour, data = whistlesBEnum, xlab = "Behaviour", ylab = "ascending")

plot(ascending ~ Behaviour, data = whistlesBEnum, xlab = "Behaviour", ylab = "ascending")

